# Generated by Django 4.0.6 on 2022-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('order', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('tag', models.ManyToManyField(to='proyecto.tag')),
            ],
        ),
    ]
