# Generated by Django 4.0.6 on 2022-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('UNI', 'Universitario'), ('CUR', 'Curso'), ('AYU', 'Ayudantia')], max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('order', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
